### ISSUE TITLE
node-sass (as dep of the docpad plugin) not installing

### ISSUE THREAD

**Issue by raucao** [67P/website#1]
```
> node-sass@1.2.3 postinstall /home/basti/src/kosmos/website/node_modules/docpad-plugin-nodesass/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/basti/src/kosmos/website/node_modules/docpad-plugin-nodesass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Linux 3.19.3-3-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
```

**Comment by galfert** [comment]
I'm getting the same error on OS X. Looks like that version of node-sass (1.2.3) is not compatible with the current libsass we have installed. The current version of node-sass is 2.1.1.

**Comment by raucao** [comment]
What's the recommended fix in such a situation? Should we try to upgrade the DocPad plugin?

**Comment by galfert** [comment]
Yes, looks like they updated the plugin 4 days ago, using a newer version of node-sass now.

**Comment by raucao** [comment]
Ah, cool.
